const rules = [
  {
    id: "R1",
    premises: { prioritas: "game", anggaran: "tinggi", baterai: "ya" },
    goal: "HP Flagship Gaming",
    desc: "gaming-flagship",
  },
  {
    id: "R1V2",
    premises: {
      prioritas: "game",
      anggaran: "tinggi", // PERBAIKAN: Ganti 'battery' menjadi 'baterai'
      baterai: "tidak",
    },
    goal: "HP Flagship Gaming Ignore Battery",
    desc: "gaming-flagship-Ignory-Battery",
  },
  {
    id: "R2",
    premises: { prioritas: "game", anggaran: "menengah", baterai: "ya" },
    goal: "HP Gaming Mid-Range",
    desc: "gaming-midrange",
  },
  {
    id: "R2V2",
    premises: { prioritas: "game", anggaran: "menengah", baterai: "tidak" },
    goal: "HP Gaming Mid-Range Ignore Battery",
    desc: "gaming-midrange-ignore-battery",
  },
  {
    id: "R3",
    premises: { prioritas: "game", anggaran: "rendah", baterai: "ya" },
    goal: "HP Gaming Entry-Level",
    desc: "gaming-entrylevel",
  },
  {
    id: "R3V2",
    premises: { prioritas: "game", anggaran: "rendah", baterai: "tidak" },
    goal: "HP Gaming Entry-Level Ignore Battery",
    desc: "gaming-entrylevel-ignore-battery",
  },
  {
    id: "R4",
    premises: { prioritas: "foto", anggaran: "tinggi", baterai: "ya" },
    goal: "HP Flagship Kamera Terbaik",
    desc: "flagship-kamera",
  },
  {
    id: "R4V2",
    premises: { prioritas: "foto", anggaran: "tinggi", baterai: "tidak" },
    goal: "HP Flagship Kamera Terbaik Ignore Battery",
    desc: "flagship-kamera-ignore-battery",
  },
  {
    id: "R5",
    premises: { prioritas: "foto", anggaran: "menengah", baterai: "ya" },
    goal: "HP Kamera Mid-Range Terbaik",
    desc: "midrange-kamera",
  },
  {
    id: "R5V2",
    premises: { prioritas: "foto", anggaran: "menengah", baterai: "tidak" },
    goal: "HP Kamera Mid-Range Terbaik Ignore Battery",
    desc: "midrange-kamera-ignore-battery",
  },
  {
    id: "R6",
    premises: { prioritas: "foto", anggaran: "rendah", baterai: "ya" },
    goal: "HP Kamera Entry-level Terbaik",
    desc: "entrylevel-kamera",
  },
  {
    id: "R6V2",
    premises: { prioritas: "foto", anggaran: "rendah", baterai: "tidak" },
    goal: "HP Kamera Entry-level Terbaik Ignore Battery",
    desc: "entrylevel-kamera-ignore-battery",
  },
  {
    id: "R7",
    premises: { prioritas: "bisnis", anggaran: "tinggi", baterai: "ya" },
    goal: "HP Bisnis Fgaship",
    desc: "hp-bisnis-flagship",
  },
  {
    id: "R7V2",
    premises: { prioritas: "bisnis", anggaran: "tinggi", baterai: "tidak" },
    goal: "HP Bisnis Fgaship Ignore Battery",
    desc: "hp-bisnis-flagship-ignore-battery",
  },
  {
    id: "R8",
    premises: { prioritas: "bisnis", anggaran: "menengah", baterai: "ya" },
    goal: "HP Bisnis Mid-Range",
    desc: "hp-bisnis-midrange",
  },
  {
    id: "R8V2",
    premises: { prioritas: "bisnis", anggaran: "menengah", baterai: "tidak" },
    goal: "HP Bisnis Mid-Range Ignore Battery",
    desc: "hp-bisnis-midrange-ignore-battery",
  },
  {
    id: "R9",
    premises: { prioritas: "bisnis", anggaran: "rendah", baterai: "ya" },
    goal: "HP Bisnis Entry Level",
    desc: "hp-bisnis-entrylevel",
  },
  {
    id: "R9V2",
    premises: { prioritas: "bisnis", anggaran: "rendah", baterai: "tidak" },
    goal: "HP Bisnis Entry Level Ignore battery",
    desc: "hp-bisnis-entrylevel-ignore-battery",
  },
  {
    id: "R9",
    premises: { prioritas: "outdoor", anggaran: "rendah", baterai: "ya" },
    goal: "HP outdoor Entry Level",
    desc: "hp-outdoor-entrylevel",
  },
  {
    id: "R9V2",
    premises: { prioritas: "outdoor", anggaran: "rendah", baterai: "tidak" },
    goal: "HP outdoor Entry Level Ignore Battery",
    desc: "hp-outdoor-entrylevel-ignore-battery",
  },
  {
    id: "R10",
    premises: { prioritas: "outdoor", anggaran: "menengah", baterai: "ya" },
    goal: "HP outdoor Mid-Range",
    desc: "hp-outdoor-midrange",
  },
  {
    id: "R10V2",
    premises: { prioritas: "outdoor", anggaran: "menengah", baterai: "tidak" },
    goal: "HP outdoor Mid-Range Ignore Battery",
    desc: "hp-outdoor-midrange-ignore-battery",
  },
  {
    id: "R11",
    premises: { prioritas: "outdoor", anggaran: "tinggi", baterai: "ya" },
    goal: "HP outdoor Flagship",
    desc: "hp-outdoor-flagship",
  },
  {
    id: "R11V2",
    premises: { prioritas: "outdoor", anggaran: "tinggi", baterai: "tidak" },
    goal: "HP outdoor Flagship Ignore Battery",
    desc: "hp-outdoor-flagship-ignore-battery",
  },
];

const prosesorGaming = [
  "mediatek dimensity 9400+",
  "qualcomm snapdragon 8 elite gen 4",
  "qualcomm snapdragon 8 elite gen 3",
  "qualcomm snapdragon 8 gen 3",
  "apple a18 pro",
  "mediatek dimensity 9400e",
  "apple A18",
  "mediatek dimensity 9400",
  "mediatek dimensity 9300+",
  "snapdragon 8s gen 4",
  "apple a17 pro",
  "mediatek dimensity 9300",
  "qualcom snapdragon 8 gen 3",
  "apple a16 bionic",
  "samsung exynos 2400",
  "samsung exynos 2400e",
  "mediatek dimensity 8450",
  "apple a15 bionic",
  "mediatek dimensity 8400",
  "mediatek dimensity 8300 ultra",
];

export { rules, prosesorGaming };
